// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shdhbfvpprqhtooqluld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoZGhiZnZwcHJxaHRvb3FsdWxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MzQ5OTYsImV4cCI6MjA3MTExMDk5Nn0.Ts_D5Sjp9rWsYhGmoiT8fRUfWUUqkBzkHimYcXSFgWg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});